Check multiple dropboxes for successful/failed batches
harvard-lts/dais-cron pull request #9
Opened 2022-09-13 20:34 UTC by jessjass

**Check multiple dropboxes for successful/failed batches**
* * *

**GitHub Issue**: [epadd#92](https://app.zenhub.com/workspaces/epadd-harvard-62c485cd49f954001312ebdd/issues/harvard-lts/epadd/92)

# What does this Pull Request do?
This PR expands the code to include a list of dropboxes to check for LOADREPORT and batch.xml.failed files

# How should this be tested?

1. Deploy to dev (this is already done through the trial branch)
2. Check logs at `/logs/hdc3a/cron`
3. Confirm the following lines are in the logs, ensuring both dropboxes are checked for successful and failed batches:
`Checking for load reports in dropbox loc: /home/appuser/dropbox/lts_load_reports/dvndev/incoming`
`Checking for load reports in dropbox loc: /home/appuser/dropbox/lts_load_reports/epadddev_secure/incoming`
`Checking failed batches in loc: /home/appuser/dropbox/dvndev/incoming`
`Checking failed batches in loc: /home/appuser/dropbox/epadddev_secure/incoming`

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? n/a
- integration tests? n/a

# Interested parties
@ives1227

2022-09-13 22:05 UTC, ives1227 requested changes
Minor code suggestions

2022-09-13 22:05 UTC, ives1227 commented on env-example.txt
> +DROPBOX_DIRS=/dvndev, /epadddev_secure
Probably best to remove the / and just list the dropbox names (more comments in code below)

2022-09-13 22:05 UTC, ives1227 commented on monitor_dropbox.py
> +        loadreport_dir = dropbox_root_dir + "/lts_load_reports" + dropbox + "/incoming"
Using the os tools can ensure that the directory separators are inserted correctly:
`loadreport_dir = os.path.join(dropbox_root_dir, "lts_load_reports", dropbox, "incoming")`

2022-09-13 22:05 UTC, ives1227 commented on monitor_dropbox.py
> +        failed_batch_dir = dropbox_root_dir + dropbox + "/incoming"
Using the os tools can ensure that the directory separators are inserted correctly:
`failed_batch_dir = os.path.join(dropbox_root_dir, droopbox, "incoming")`

2022-09-14 00:51 UTC, ives1227 requested changes
One more minor change (need to import the library)

2022-09-14 00:51 UTC, ives1227 commented on monitor_dropbox.py
> +        loadreport_dir = os.path.join(dropbox_root_dir, "lts_load_reports", dropbox, "incoming")
Make sure you import os.path (it is different than os which is confusing).

2022-09-14 13:27 UTC, jessjass commented on monitor_dropbox.py
> +        loadreport_dir = os.path.join(dropbox_root_dir, "lts_load_reports", dropbox, "incoming")
Fixed!

2022-09-14 13:50 UTC, ives1227 approved these changes

2022-09-14 13:50 UTC, merged